// Per-demo privacy gate: a private demo's host answers with a common
// access page until the visitor presents the demo's access key, which
// issues a host-only cookie. The key itself is generated by the control
// plane (shown to the creator once) and stored hashed only; the cookie
// value is an HMAC over the demo id and key hash, so rotating the key
// invalidates every issued cookie without any server-side state.
package server

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"net/url"
	"strings"
	"time"

	"democtl/internal/serving"
	"democtl/internal/store"
)

const (
	// accessCookieName is set on the demo host itself — host-only by the
	// absence of a Domain attribute, so each private demo unlocks
	// independently and the control-plane cookie stays unrelated.
	accessCookieName = "democtl_access"
	accessCookieTTL  = 7 * 24 * time.Hour // mirrors auth.SessionTTL
	// verifyPath lives under a dot-segment on purpose: serving's
	// cleanURLPath rejects dot-prefixed path segments for demo files, so
	// no deployed site can ever shadow (or be shadowed by) this route.
	verifyPath = "/.democtl/access/verify"
	// accessHMACLabel domain-separates the gate token from every other
	// use of the session key.
	accessHMACLabel = "demo-access-v1"
	// Verify rate limit: max attempts per window per remote address. The
	// edge proxy is the remote address for every visitor, so this is a
	// generous shared cap — keys are 20 random chars and brute force is
	// hopeless anyway; the limit exists to keep a scripted key sweep
	// from hammering the DB.
	verifyRateMax   = 30
	verifyRateWindow = time.Minute
)

// hashAccessKey is the at-rest form of a demo access key: sha256 hex
// (house rule: tokens hashed at rest). Compared constant-time; never
// logged, never serialized.
func hashAccessKey(key string) string {
	sum := sha256.Sum256([]byte(key))
	return hex.EncodeToString(sum[:])
}

// generateAccessKey mints a fresh access key (15 random bytes, base64url —
// 20 chars, no ambiguous padding). The plaintext leaves the server exactly
// once, in the response of the request that created or rotated it.
func generateAccessKey() (string, string, error) {
	buf := make([]byte, 15)
	if _, err := rand.Read(buf); err != nil {
		return "", "", fmt.Errorf("gate: generate access key: %w", err)
	}
	key := base64.RawURLEncoding.EncodeToString(buf)
	return key, hashAccessKey(key), nil
}

// accessToken derives the cookie value for an unlocked private demo:
// hex(HMAC-SHA256(session key, label|demo id|key hash)). Binding to the id
// (not the name, which renames) and the key hash (which rotates) means the
// token survives a rename and dies with a key rotation — no server-side
// per-visitor state exists.
func accessToken(secret string, demoID int64, keyHash string) string {
	mac := hmac.New(sha256.New, []byte(secret))
	fmt.Fprintf(mac, "%s|%d|%s", accessHMACLabel, demoID, keyHash)
	return hex.EncodeToString(mac.Sum(nil))
}

// validAccessToken recomputes and constant-time compares. Both sides are
// fixed 64-char hex strings, so the comparison leaks nothing.
func validAccessToken(secret, token string, demoID int64, keyHash string) bool {
	want := accessToken(secret, demoID, keyHash)
	return subtle.ConstantTimeCompare([]byte(want), []byte(token)) == 1
}

// gateWindow is one remote address's verify-attempt counters.
type gateWindow struct {
	count int
	reset time.Time
}

// allowVerify reports whether another access-key attempt is permitted from
// remoteAddr (fixed window). Prunes expired windows as it goes; if the map
// ever grows past a safety bound it is reset wholesale — the limiter is
// best-effort, not a security boundary.
func (s *Server) allowVerify(remoteAddr string) bool {
	s.gateMu.Lock()
	defer s.gateMu.Unlock()
	now := time.Now()
	if s.gateWindows == nil {
		s.gateWindows = make(map[string]gateWindow)
	}
	for k, w := range s.gateWindows {
		if now.After(w.reset) {
			delete(s.gateWindows, k)
		}
	}
	if len(s.gateWindows) > 8192 {
		s.gateWindows = make(map[string]gateWindow)
	}
	w := s.gateWindows[remoteAddr]
	if now.After(w.reset) {
		w = gateWindow{count: 0, reset: now.Add(verifyRateWindow)}
	}
	w.count++
	s.gateWindows[remoteAddr] = w
	return w.count <= verifyRateMax
}

// demoGate wraps static demo serving with the per-demo privacy gate.
// Public demos pass through untouched; private demos demand a valid access
// cookie and otherwise see the common access page. Unknown hosts and
// labels fall through to the wrapped handler so the generic 404 keeps
// disclosing nothing about which labels exist.
func (s *Server) demoGate(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		label, ok := serving.LabelFromHost(r.Host, s.Cfg.BaseDomain)
		if !ok {
			next.ServeHTTP(w, r)
			return
		}
		demo, err := s.DB.DemoByName(label)
		if err != nil {
			// Unknown label or lookup failure: hand over to serving,
			// whose generic 404 never distinguishes them.
			next.ServeHTTP(w, r)
			return
		}
		if !demo.Private {
			next.ServeHTTP(w, r)
			return
		}
		if r.URL.Path == verifyPath && r.Method == http.MethodPost {
			s.handleAccessVerify(w, r, demo)
			return
		}
		if c, err := r.Cookie(accessCookieName); err == nil &&
			validAccessToken(s.Cfg.SessionKey, c.Value, demo.ID, demo.AccessKeyHash) {
			next.ServeHTTP(privateResponseWriter{w}, r)
			return
		}
		// Locked. The access page renders at / itself (the URL the
		// visitor typed); deeper paths bounce there with a ?next= bookmark.
		if r.URL.Path == "/" {
			writeAccessPage(w, label+"."+s.Cfg.BaseDomain)
			return
		}
		next := r.URL.EscapedPath()
		if r.URL.RawQuery != "" {
			next += "?" + r.URL.RawQuery
		}
		http.Redirect(w, r, "/?next="+url.QueryEscape(next), http.StatusFound)
	})
}

// handleAccessVerify checks a submitted access key and, on match, issues
// the gate cookie. Responses are fixed-shape JSON; nothing about the
// stored key is ever logged or audited — unlocking is anonymous by design.
func (s *Server) handleAccessVerify(w http.ResponseWriter, r *http.Request, demo store.Demo) {
	w.Header().Set("Content-Type", "application/json")
	if host, _, err := net.SplitHostPort(r.RemoteAddr); err == nil {
		r.RemoteAddr = host
	}
	if !s.allowVerify(r.RemoteAddr) {
		w.WriteHeader(http.StatusTooManyRequests)
		w.Write([]byte(`{"ok":false}`))
		return
	}
	var body struct {
		Key string `json:"key"`
	}
	if err := json.NewDecoder(http.MaxBytesReader(w, r.Body, 4<<10)).Decode(&body); err != nil || body.Key == "" {
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte(`{"ok":false}`))
		return
	}
	got := hashAccessKey(body.Key)
	if subtle.ConstantTimeCompare([]byte(got), []byte(demo.AccessKeyHash)) != 1 {
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(`{"ok":false}`))
		return
	}
	http.SetCookie(w, &http.Cookie{
		Name:     accessCookieName,
		Value:    accessToken(s.Cfg.SessionKey, demo.ID, demo.AccessKeyHash),
		Path:     "/",
		MaxAge:   int(accessCookieTTL.Seconds()),
		HttpOnly: true,
		Secure:   s.SecureCookie,
		SameSite: http.SameSiteLaxMode,
	})
	w.Write([]byte(`{"ok":true}`))
}

// privateResponseWriter overrides the cache/robots headers on everything
// served from an unlocked private demo — the file server's own public
// caching policy must not apply to gated content, 404s included.
type privateResponseWriter struct {
	http.ResponseWriter
}

func (p privateResponseWriter) WriteHeader(code int) {
	h := p.Header()
	h.Set("Cache-Control", "private, no-store")
	h.Set("X-Robots-Tag", "noindex, nofollow")
	p.ResponseWriter.WriteHeader(code)
}

// writeAccessPage renders the common access page for a locked demo; host
// is the demo's full host name (label.<BaseDomain>).
func writeAccessPage(w http.ResponseWriter, host string) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("X-Robots-Tag", "noindex, nofollow")
	w.Header().Set("Referrer-Policy", "no-referrer")
	w.Header().Set("Content-Security-Policy",
		"default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; "+
			"connect-src 'self'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	// Token replacement, not a format string: the document is mostly CSS
	// full of literal % signs.
	fmt.Fprint(w, strings.ReplaceAll(accessPageHTML, "{{HOST}}", host))
}

// accessPageHTML is the whole gate: markup, styling, and the unlock script
// in one standalone document — no external assets, so it renders before
// any demo content is (or could be) loaded. The label interpolates
// %s-safely: it comes through LabelFromHost + DemoByName, and demo names
// are [a-z0-9-] by construction.
const accessPageHTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow, noarchive">
<title>Private demo — {{HOST}}</title>
<style>
  * { box-sizing: border-box; margin: 0; }
  body {
    min-height: 100vh; display: flex; align-items: center; justify-content: center;
    background: #f4f5f3; color: #1d1f1c;
    font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
    padding: 24px;
  }
  .card {
    width: 100%; max-width: 380px; background: #fff; border-radius: 12px;
    padding: 32px 28px; box-shadow: 0 8px 30px rgba(20, 30, 20, .08);
    border-top: 4px solid #2f7d4f;
  }
  h1 { font-size: 20px; font-weight: 600; margin-bottom: 6px; }
  p.sub { color: #5a6058; font-size: 14px; line-height: 1.5; margin-bottom: 20px; }
  code { background: #eef0ec; border-radius: 4px; padding: 1px 5px; font-size: 13px; }
  input[type=password] {
    width: 100%; padding: 11px 12px; font-size: 15px; border: 1px solid #cdd2ca;
    border-radius: 8px; margin-bottom: 12px; outline: none;
  }
  input[type=password]:focus { border-color: #2f7d4f; }
  button {
    width: 100%; padding: 11px 0; font-size: 15px; font-weight: 600; color: #fff;
    background: #2f7d4f; border: 0; border-radius: 8px; cursor: pointer;
  }
  button:disabled { opacity: .6; cursor: wait; }
  .error {
    display: none; margin-top: 14px; padding: 9px 12px; border-radius: 8px;
    background: #fbeaea; color: #a33; font-size: 13px; line-height: 1.4;
  }
  .hint { margin-top: 18px; color: #7a8078; font-size: 12px; line-height: 1.5; }
  @keyframes shake {
    0%, 100% { transform: translateX(0); }
    25% { transform: translateX(-6px); } 75% { transform: translateX(6px); }
  }
  .shake { animation: shake .3s ease-in-out; }
  @media (prefers-color-scheme: dark) {
    body { background: #14171a; color: #e6e8e4; }
    .card { background: #1d2126; box-shadow: 0 8px 30px rgba(0,0,0,.45); }
    p.sub, .hint { color: #9aa39c; }
    code { background: #2a2f36; }
    input[type=password] { background: #14171a; color: #e6e8e4; border-color: #3a4148; }
    .error { background: #341c1c; color: #e08a8a; }
  }
</style>
</head>
<body>
<main class="card" id="card">
  <h1>This demo is private</h1>
  <p class="sub">Enter the access key for <code>{{HOST}}</code> to continue.</p>
  <noscript><p class="sub">Unlocking this demo requires JavaScript.</p></noscript>
  <form id="f" autocomplete="off">
    <input type="password" id="key" aria-label="Access key" autofocus>
    <button type="submit" id="go">Unlock</button>
  </form>
  <div class="error" id="err"></div>
  <p class="hint">Ask the demo's owner for the key.</p>
</main>
<script>
(function () {
  var form = document.getElementById('f');
  var input = document.getElementById('key');
  var button = document.getElementById('go');
  var err = document.getElementById('err');
  var card = document.getElementById('card');
  function fail(msg, shake) {
    err.textContent = msg;
    err.style.display = 'block';
    if (shake) {
      card.classList.remove('shake');
      void card.offsetWidth; /* restart the animation */
      card.classList.add('shake');
    }
    input.value = '';
    input.focus();
    button.disabled = false;
  }
  form.addEventListener('submit', function (event) {
    event.preventDefault();
    err.style.display = 'none';
    button.disabled = true;
    fetch('/.democtl/access/verify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ key: input.value })
    }).then(function (r) {
      if (r.ok) {
        var next = new URLSearchParams(location.search).get('next') || '/';
        /* only same-site absolute paths — never protocol-relative */
        if (next.charAt(0) !== '/' || next.charAt(1) === '/' || next.charAt(1) === '\\') {
          next = '/';
        }
        location.replace(next);
        return;
      }
      if (r.status === 429) { fail('Too many attempts — wait a minute and try again.', false); return; }
      fail('That key is not right. Check with the owner and try again.', true);
    }).catch(function () {
      fail('Could not reach the server — try again.', false);
    });
  });
})();
</script>
</body>
</html>
`
